# -*- coding: utf-8 -*-
"""Robot Obstacle Avoidance

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gXMUxCpsJLq7WPDEfLLBHOBB0DvFeZhe
"""

import time
import random

def get_distance():
    return random.randint(5, 100)

def decide_move(distance):
    if distance < 10:
        return "Stop"
    if distance < 20:
        return "Turn Right"
    if distance < 30:
        return "Turn Left"
    return "Move Forward"

while True:
    dist = get_distance()
    action = decide_move(dist)
    print(f"Distance: {dist} cm   Action: {action}")
    time.sleep(1)